### ISSUE TITLE
TypeError: restify.acceptParser is not a function

### ISSUE THREAD

**Issue by menzil** [roymax/moquery#1]
/moquery/app.js:8
server.use(restify.acceptParser(server.acceptable));
TypeError: restify.acceptParser is not a function
    at Object.<anonymous> (/Users/nur/Documents/github/moquery/app.js:8:20)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

**Comment by roymax** [comment]
这个代码和依赖的库都太老了，我已不确定它是否能跑起来

**Comment by menzil** [comment]
@roymax 哦，我看到你在cnode上的帖子，我们需求一样，没注意到时间。谢谢！

**Comment by roymax** [comment]
看你需求，这个不难
